# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: D:/Tsinghua/2018autumn/VivadoProject/thinpad_top/thinpad_top.srcs/sources_1/ip/pll_example/pll_example.xci
# IP: The module: 'pll_example' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Tsinghua/2018autumn/VivadoProject/thinpad_top/thinpad_top.srcs/sources_1/ip/pll_example/pll_example_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_example'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Tsinghua/2018autumn/VivadoProject/thinpad_top/thinpad_top.srcs/sources_1/ip/pll_example/pll_example.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_example'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Tsinghua/2018autumn/VivadoProject/thinpad_top/thinpad_top.srcs/sources_1/ip/pll_example/pll_example_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_example'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# IP: D:/Tsinghua/2018autumn/VivadoProject/thinpad_top/thinpad_top.srcs/sources_1/ip/pll_example/pll_example.xci
# IP: The module: 'pll_example' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: d:/Tsinghua/2018autumn/VivadoProject/thinpad_top/thinpad_top.srcs/sources_1/ip/pll_example/pll_example_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_example'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Tsinghua/2018autumn/VivadoProject/thinpad_top/thinpad_top.srcs/sources_1/ip/pll_example/pll_example.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_example'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet

# XDC: d:/Tsinghua/2018autumn/VivadoProject/thinpad_top/thinpad_top.srcs/sources_1/ip/pll_example/pll_example_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'pll_example'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells inst -quiet] -quiet
